name: Github Actions Demo CI
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install PNPM
        run: npm install -g pnpm

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: pnpm build

      # - name: Deploy
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.ACTION_TOKEN }}
      #     publish_dir: ./dist

      - name: deploy project
        uses: easingthemes/ssh-deploy@v2.2.11
        with: 
          remote_host: ${{ secrets.REMOTE_HOST }}
          remote_user: 'deployuser'
          ssh_private_key: ${{ secrets.REMOTE_KEY }}
          args: '-avzr --delete'
          source: 'build'
          target: '/var/www/html/github-action.html'
